"""initial schema: connection_config, mapping, enum_translation, run_log

Revision ID: 0ce07b093da6
Revises:
Create Date: 2026-09-09 15:48:04.262139

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ce07b093da6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connection_config",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "role", sa.Enum("source", "target", "either", name="connection_role"), nullable=False
        ),
        sa.Column(
            "environment",
            sa.Enum("dev", "test", "prod", name="connection_environment"),
            nullable=False,
        ),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("database", sa.String(length=200), nullable=False),
        sa.Column("credential_ref", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "enum_translation_table",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["enum_translation_version.id"],
            name="fk_current_translation_version",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "enum_translation_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("enum_translation_table_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("entries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enum_translation_table_id"],
            ["enum_translation_table.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enum_translation_table_id", "version_number"),
    )
    op.create_table(
        "mapping_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind", sa.Enum("column_mapping", "retirement", name="mapping_kind"), nullable=False
        ),
        sa.Column("source_connection_id", sa.UUID(), nullable=False),
        sa.Column("source_table", sa.String(length=400), nullable=False),
        sa.Column("target_connection_id", sa.UUID(), nullable=False),
        sa.Column("target_table", sa.String(length=400), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["mapping_version.id"],
            name="fk_current_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["source_connection_id"],
            ["connection_config.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_connection_id"],
            ["connection_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "mapping_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mapping_definition_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("column_links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retirement_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("row_identity_column", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mapping_definition_id"],
            ["mapping_definition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mapping_definition_id", "version_number"),
    )
    op.create_table(
        "run_log_entry",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("mapping_version_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.Enum("dry_run", "execute", name="run_mode"), nullable=False),
        sa.Column("operator", sa.String(length=200), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("completed", "partially_completed", "failed", name="run_outcome"),
            nullable=True,
        ),
        sa.Column("source_rows_read", sa.Integer(), nullable=False),
        sa.Column("target_rows_written", sa.Integer(), nullable=False),
        sa.Column("retirement_records_written", sa.Integer(), nullable=False),
        sa.Column("untranslatable_rows_flagged", sa.Integer(), nullable=False),
        sa.Column("sample_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("production_confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mapping_version_id"],
            ["mapping_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("run_log_entry")
    op.drop_table("mapping_version")
    op.drop_table("mapping_definition")
    op.drop_table("enum_translation_version")
    op.drop_table("enum_translation_table")
    op.drop_table("connection_config")
    # ### end Alembic commands ###
