"""add legacy shape, view definition, deployment log, reconciliation, xml field mapping tables

Revision ID: 19be2c2b2a13
Revises: 0ce07b093da6
Create Date: 2026-09-09 20:23:59.871598

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "19be2c2b2a13"
down_revision: str | Sequence[str] | None = "0ce07b093da6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_shape_capture",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("table_name", sa.String(length=400), nullable=False),
        sa.Column("columns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connection_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "view_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("legacy_shape_capture_id", sa.UUID(), nullable=False),
        sa.Column("target_connection_id", sa.UUID(), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["view_definition_version.id"],
            name="fk_current_view_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["legacy_shape_capture_id"],
            ["legacy_shape_capture.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_connection_id"],
            ["connection_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "xml_field_mapping",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("legacy_shape_capture_id", sa.UUID(), nullable=False),
        sa.Column("xml_connection_id", sa.UUID(), nullable=False),
        sa.Column("xml_table_name", sa.String(length=400), nullable=False),
        sa.Column("xml_identity_column", sa.String(length=200), nullable=False),
        sa.Column("xml_payload_column", sa.String(length=200), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_version_id"],
            ["xml_field_mapping_version.id"],
            name="fk_current_xml_mapping_version",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["legacy_shape_capture_id"],
            ["legacy_shape_capture.id"],
        ),
        sa.ForeignKeyConstraint(
            ["xml_connection_id"],
            ["connection_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "view_definition_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("view_definition_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("join_graph", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("column_mappings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_sql", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["view_definition_id"],
            ["view_definition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("view_definition_id", "version_number"),
    )
    op.create_table(
        "xml_field_mapping_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("xml_field_mapping_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("field_paths", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["xml_field_mapping_id"],
            ["xml_field_mapping.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("xml_field_mapping_id", "version_number"),
    )
    op.create_table(
        "reconciliation_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("view_definition_version_id", sa.UUID(), nullable=False),
        sa.Column("identity_column", sa.String(length=200), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum("completed", "partially_completed", "failed", name="reconciliation_outcome"),
            nullable=True,
        ),
        sa.Column("rows_matched", sa.Integer(), nullable=False),
        sa.Column("rows_old_only", sa.Integer(), nullable=False),
        sa.Column("rows_view_only", sa.Integer(), nullable=False),
        sa.Column("rows_with_column_mismatch", sa.Integer(), nullable=False),
        sa.Column("row_inflation_flagged", sa.Boolean(), nullable=False),
        sa.Column("discrepancy_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["view_definition_version_id"],
            ["view_definition_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "view_deployment_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("view_definition_version_id", sa.UUID(), nullable=False),
        sa.Column("mode", sa.Enum("preview", "deploy", name="deployment_mode"), nullable=False),
        sa.Column("operator", sa.String(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "outcome", sa.Enum("completed", "failed", name="deployment_outcome"), nullable=True
        ),
        sa.Column("sample_rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("column_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("production_confirmed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["view_definition_version_id"],
            ["view_definition_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        "fk_current_translation_version",
        "enum_translation_table",
        "enum_translation_version",
        ["current_version_id"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_current_version",
        "mapping_definition",
        "mapping_version",
        ["current_version_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_current_version", "mapping_definition", type_="foreignkey")
    op.drop_constraint(
        "fk_current_translation_version", "enum_translation_table", type_="foreignkey"
    )
    op.drop_table("view_deployment_log")
    op.drop_table("reconciliation_run")
    op.drop_table("xml_field_mapping_version")
    op.drop_table("view_definition_version")
    op.drop_table("xml_field_mapping")
    op.drop_table("view_definition")
    op.drop_table("legacy_shape_capture")
    # ### end Alembic commands ###
