"""add legacy_view_column_rule table

Revision ID: b99f4d8be5e0
Revises: 19be2c2b2a13
Create Date: 2026-09-09 22:54:33.204848

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b99f4d8be5e0"
down_revision: str | Sequence[str] | None = "19be2c2b2a13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_view_column_rule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("view_definition_version_id", sa.UUID(), nullable=False),
        sa.Column("legacy_table_name", sa.String(length=400), nullable=False),
        sa.Column("compatibility_view_name", sa.String(length=200), nullable=False),
        sa.Column("column_name", sa.String(length=200), nullable=False),
        sa.Column("column_status", sa.String(length=20), nullable=False),
        sa.Column("expected_null_flag", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["view_definition_version_id"],
            ["view_definition_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        "fk_current_view_version",
        "view_definition",
        "view_definition_version",
        ["current_version_id"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_current_xml_mapping_version",
        "xml_field_mapping",
        "xml_field_mapping_version",
        ["current_version_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_current_xml_mapping_version", "xml_field_mapping", type_="foreignkey")
    op.drop_constraint("fk_current_view_version", "view_definition", type_="foreignkey")
    op.drop_table("legacy_view_column_rule")
    # ### end Alembic commands ###
