"""add auth_mode and username to connection_config

Revision ID: da2a38d4d1f8
Revises: b99f4d8be5e0
Create Date: 2026-09-10 10:45:42.390362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da2a38d4d1f8"
down_revision: str | Sequence[str] | None = "b99f4d8be5e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows (created before auth_mode existed) are all SQL-auth connections —
    # backfill them with server_default='sql' rather than leaving the column
    # unfillable on a non-empty table, then drop the default so future inserts must
    # state auth_mode explicitly (the ORM/API always does).
    auth_mode_enum = sa.Enum("sql", "windows_integrated", name="connection_auth_mode")
    auth_mode_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "connection_config",
        sa.Column(
            "auth_mode",
            auth_mode_enum,
            nullable=False,
            server_default="sql",
        ),
    )
    op.alter_column("connection_config", "auth_mode", server_default=None)
    op.add_column("connection_config", sa.Column("username", sa.String(length=200), nullable=True))
    op.alter_column(
        "connection_config", "credential_ref", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "connection_config", "credential_ref", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.drop_column("connection_config", "username")
    op.drop_column("connection_config", "auth_mode")
    sa.Enum(name="connection_auth_mode").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
